# SwiftLint Configuration for Shell iOS Project

# Paths to include/exclude
included:
  - Shell
  - ShellTests
  - ShellUITests

excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData
  - vendor

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - line_length

# Rule configurations
identifier_name:
  min_length: 2
  max_length: 60
  excluded:
    - id
    - db
    - x
    - y
    - z

type_name:
  min_length: 3
  max_length: 50

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level: 2
  function_level: 3

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  no_print:
    name: "Print Usage"
    regex: "\\bprint\\("
    match_kinds:
      - identifier
    message: "Use os_log instead of print"
    severity: warning

  no_nslog:
    name: "NSLog Usage"
    regex: "\\bNSLog\\("
    match_kinds:
      - identifier
    message: "Use os_log instead of NSLog"
    severity: warning

# Reporter type
reporter: "xcode"
